name: INTEMPT-TASK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
      - name: "triger repo"
        run: |
           curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/felixphilipk/Test-Api-Intempt/dispatches --data '{"event_type": "build_application"}'    


